name = "workers-graphql-server"
main = "./src/index.js"
node_compat = true
workers_dev = true
compatibility_date = "2023-09-09"


# Enable a kv-namespace to use the KV caching feature
#
# kv-namespaces = [
#   { binding = "WORKERS_GRAPHQL_CACHE", id = "" }
# ]

[build]
command = "npm install"

[site]
include = ["./"]



[dev]
ip = "0.0.0.0"
port = 8787
local_protocol="http"
upstream_protocol="https"
