name: Deploy to Cloudflare Workers

on: workflow_dispatch
   
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        uses: cloudflare/wrangler-action@v3.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: "3.7.0"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
